---
on:
    push:
        branches:
            - main

jobs:
    deploy:
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: 'Az CLI login'
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - name: Deploy infra
              run: |
                az deployment group create --resource-group vm-application --template-file infra/main.bicep --parameter mediaLink='${{ secrets.MEDIA_LINK }}'